version: "3.8"

services:
  node0:
    build: .
    hostname: node0
    container_name: node0
    ports:
      - "8081:8081"
    environment:
      - SERVER_ID=0
    volumes:
      - ./node0_data:/data

  node1:
    build: .
    hostname: node1
    container_name: node1
    ports:
      - "8082:8081"
    environment:
      - SERVER_ID=1
    volumes:
      - ./node1_data:/data
  node2:
    build: .
    hostname: node2
    container_name: node2
    ports:
      - "8083:8081"
    environment:
      - SERVER_ID=2
    volumes:
      - ./node2_data:/data
  node3:
    build: .
    hostname: node3
    container_name: node3
    ports:
      - "8084:8081"
    environment:
      - SERVER_ID=3
    volumes:
      - ./node3_data:/data
  node4:
    build: .
    hostname: node4
    container_name: node4
    ports:
      - "8085:8081"
    environment:
      - SERVER_ID=4
    volumes:
      - ./node4_data:/data
